name: Saving blobs
 
on:
    push:
        branches: [ main ]

    workflow_dispatch:

    schedule:
        - cron: '0 0,12 * * *'

env:
    TZ: UTC

jobs: 
    build: 
        runs-on: ubuntu-latest
        steps: 
            - 
                uses: actions/checkout@v2
            - 
                name: Saving shsh
                run: |
                    wget ${{ secrets.jsonURL }} -O data.json >& /dev/null
                    python3 main.py
            - 
               name: Delete workflow runs
               uses: GitRML/delete-workflow-runs@main
               with:
                 retain_days: 3
                 keep_minimum_runs: 0  
